default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  database: <%= ENV["DATABASE"] %>

development:
  <<: *default
  template: template0

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
